### ISSUE TITLE
arrangeGrob Documentation has Incorrect Information

### ISSUE THREAD

**Issue by DarioS** [baptiste/gridextra#24]
The function definition of `grid.arrange` is `grid.arrange(..., newpage = TRUE)` and `...` is described as "grobs, gtables, ggplot or trellis objects". However, parameters such as `nrow` are also accepted and have an effect, although they are not any of the listed objects.

In the Values section, there is no entry for `grid.arrange`, even though it also returns a `gtable`.

It seems that `grid.arrange` and `arrangeGrob` are almost exactly the same. Why not just have one function, with a plot option ? e.g `grid.arrange(onePlot, otherPlot, plot = FALSE)`

The Functions section appears last. Would it be better if it was immediately after the Usage section ?

**Comment by baptiste** [comment]
having two separate functions is a convention of the grid package; I agree the documentation isn't very clear since both functions are on the same page with different meaning of `...`. One option would be to copy explicitly all the parameters as in `grid.arrange = function(..., ncol) arrangeGrob(..., ncol=ncol), I'll try to do that when I find the time (it's a rather low priority).
