### ISSUE TITLE
join renamed combine

### ISSUE THREAD

**Issue by smsaladi** [baptiste/gridextra#30]
I understand the logic of renaming `join` to `combine`, but for backwards compatibility/easier debugging, would it be possible to raise a more informative error when code attempts to call `gridExtra::join`?

Right now, the following generic message comes up:
> Error: 'join' is not an exported object from 'namespace:gridExtra'

**Comment by baptiste** [comment]
I'd rather rename it `join` in the future, it's more natural. Unfortunately `dplyr` has a cavalier attitude towards namespaces which forced me to make this dubious change (and in fact dplyr also masks `combine`, as I later found out). So my advice would be not to rely on `gridExtra::combine` for now (it's rather experimental with some shortcomings). The generic message is standard for a function that doesn't exist, and since `join` was only there only for a very brief period I'm not much inclined to add a back-compatibility warning. Sorry about the inconvenience, but gtable and dplyr don't make things easy for other package developers.
