### ISSUE TITLE
Submit new version with ggplotGrob fix to CRAN

### ISSUE THREAD

**Issue by daattali** [baptiste/gridextra#5]
[Your fix from half a year ago](06b65cab23f2c1dfd8551e43f917ff2b557da222) fixes a blocking bug that prevents me from being able to use gridExtra in my package. Can you please have the fix in the official CRAN version so that everyone will have the fix? :)

**Comment by baptiste** [comment]
the link is broken

**Comment by daattali** [comment]
Sorry, it's the latest commit 06b65cab23f2c1dfd8551e43f917ff2b557da222

**Comment by baptiste** [comment]
the larger issue here is that if I submit a CRAN update, it will probably not get accepted because of tighter quality checks. I would have to spend a considerable amount of time cleaning up the package, and I don't have such free time. 
I made an informal poll with package maintainers depending on gridExtra, trying to figure out what functions are really needed, and it turns out that only grid.arrange (and grid.table to a minor extent) is in use. In this view, I suggested that the function be moved to either grid or gtable, but neither Hadley nor Paul have followed up on this, and no-one offered to take over maintenance of gridExtra.

**Comment by daattali** [comment]
I see. In that case, I have two questions (sorry if it's not the most appropriate place to ask)

- I also use `arrangeGrob`, but that's just because I can't get grid.arrange to suppress its plotting side-effect. I tried supplying a `plot=FALSE` argument but it still plots. Is there a way to not have grid.arrange output the plot?

- Do you have a recommendation on what to do in order to use grid.arrange in a package? Currently I'm getting `Error: could not find function "ggplotGrob"`, I was wondering if you know of the proper solution since you might have more experience with this than me

Thank you for being so prompt

**Comment by baptiste** [comment]
- grid grobs generally come in two flavours, `xxxGrob` and `grid.xxx` where the former doesn't draw anything directly. If you don't want immediate drawing, use `arrangeGrob`.

- not really, no. `ggplotGrob` is a function in ggplot2, so you could try importing it, or even `Depends:` on the ggplot2 package. Complying with CRAN policies in those matters can be tricky.
